name: convid-19
channels:
  - conda-forge
dependencies:
  - python=3.7
  - pytorch
  - torchsummary
  - statsmodels
  - nodejs
  - jupyterlab>=2.0.0
  - numpy>=1.18.1
  - h5py
  - scipy>=1.3.0
  - toolz
  - bokeh>=2.0.0
  - dask=2.11.0
  - dask-labextension>=2.0.0
  - distributed=2.11.0
  - notebook
  - matplotlib
  - pandas>=1.0.1
  - pandas-datareader
  - pytables
  - scikit-learn>=0.22.1
  - scikit-image>=0.15.0
  - dask-ml
  - python-graphviz